### ISSUE TITLE
/root/komodoGUI/src/build/build.xml:136: JAVA_HOME has to be set!

### ISSUE THREAD

**Issue by erezrb** [ca333/komodoGUI#1]
Hi,

i try to build ant that this is the error i'm getting:

/root/komodoGUI/src/build/build.xml:136: JAVA_HOME has to be set!

**Comment by ca333** [comment]
like stated in the error ouput you have to set your java home path:
`export JAVA_HOME=YOUR_JAVA_HOME_PATH`
