### ISSUE TITLE
'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds

### ISSUE THREAD

**Issue by erezrb** [ca333/komodoGUI#2]
ant -buildfile ./src/build/build.xml release
Buildfile: /root/komodoGUI/src/build/build.xml

checkJavaHome:

compile:
    [javac] /root/komodoGUI/src/build/build.xml:83: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
    [javac] Compiling 40 source files to /root/komodoGUI/build/classes
    [javac] Note: /root/komodoGUI/src/java/com/vaklinov/zcashui/DashboardPanel.java uses or overrides a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.

copyResources:

jar:
      [jar] Building jar: /root/komodoGUI/build/jars/KomodoSwingWalletUI.jar

release:
  [taskdef] Could not load definitions from resource com/sun/javafx/tools/ant/antlib.xml. It could not be found.

BUILD FAILED
/root/komodoGUI/src/build/build.xml:157: Problem: failed to create task or type javafx:com.sun.javafx.tools.ant:application
Cause: The name is undefined.
Action: Check the spelling.
Action: Check that any custom tasks/types have been declared.
Action: Check that any <presetdef>/<macrodef> declarations have taken place.
No types or tasks have been defined in this namespace yet

Total time: 12 seconds
root@kmd:~/komodoGUI#

**Comment by ca333** [comment]
you have to set your java home path

**Comment by njappboy** [comment]
@erezrb @ca333 User's will also see this issue if they are not running Java 7 with Update 6 or better. Some nix based users may install an older version using `apt-get` or `yum`  package managers. The javafx ant library will not be present in the early version of Java 7.
https://docs.oracle.com/javase/9/deploy/javafx-ant-tasks.htm#JSDPG177

**Comment by njappboy** [comment]
Additional reference https://stackoverflow.com/questions/34243982/why-is-javafx-is-not-included-in-openjdk-8-on-ubuntu-wily-15-10
